export const emojis = [
    { emoji: '😀', name: 'Smile' },
    { emoji: '😂', name: 'Laugh' },
    { emoji: '😭', name: 'Crying' },
    { emoji: '😡', name: 'Angry' },
    { emoji: '😴', name: 'Sleepy' },
    { emoji: '🤔', name: 'Thinking' },
    { emoji: '😍', name: 'Love' },
    { emoji: '😎', name: 'Cool' },
    { emoji: '🥶', name: 'Cold' },
    { emoji: '😱', name: 'Scared' },

    { emoji: '🐶', name: 'Dog' },
    { emoji: '🐱', name: 'Cat' },
    { emoji: '🐭', name: 'Mouse' },
    { emoji: '🐰', name: 'Rabbit' },
    { emoji: '🦊', name: 'Fox' },
    { emoji: '🐼', name: 'Panda' },
    { emoji: '🐸', name: 'Frog' },
    { emoji: '🐵', name: 'Monkey' },
    { emoji: '🐷', name: 'Pig' },
    { emoji: '🦁', name: 'Lion' },

    { emoji: '🌮', name: 'Taco' },
    { emoji: '🍕', name: 'Pizza' },
    { emoji: '🍔', name: 'Burger' },
    { emoji: '🍣', name: 'Sushi' },
    { emoji: '🍩', name: 'Donut' },
    { emoji: '🍎', name: 'Apple' },
    { emoji: '🍌', name: 'Banana' },
    { emoji: '🍓', name: 'Strawberry' },
    { emoji: '🥦', name: 'Broccoli' },
    { emoji: '🥚', name: 'Egg' },

    { emoji: '🚗', name: 'Car' },
    { emoji: '✈️', name: 'Airplane' },
    { emoji: '🚀', name: 'Rocket' },
    { emoji: '🚌', name: 'Bus' },
    { emoji: '🚲', name: 'Bicycle' },
    { emoji: '🚂', name: 'Train' },
    { emoji: '🚁', name: 'Helicopter' },
    { emoji: '🛳️', name: 'Ship' },
    { emoji: '🏍️', name: 'Motorcycle' },
    { emoji: '🚜', name: 'Tractor' },

    { emoji: '🎉', name: 'Party' },
    { emoji: '🎵', name: 'Music' },
    { emoji: '🎨', name: 'Art' },
    { emoji: '📚', name: 'Books' },
    { emoji: '💡', name: 'Idea' },
    { emoji: '🕹️', name: 'Game' },
    { emoji: '📷', name: 'Camera' },
    { emoji: '🎬', name: 'Movie' },
    { emoji: '🧩', name: 'Puzzle' },
    { emoji: '🎮', name: 'Console' },

    { emoji: '🌍', name: 'Earth' },
    { emoji: '☀️', name: 'Sun' },
    { emoji: '🌧️', name: 'Rain' },
    { emoji: '⛄', name: 'Snowman' },
    { emoji: '🌈', name: 'Rainbow' },
    { emoji: '🔥', name: 'Fire' },
    { emoji: '💧', name: 'Water' },
    { emoji: '🍁', name: 'Leaf' },
    { emoji: '🌙', name: 'Moon' },
    { emoji: '⚡', name: 'Lightning' }
];